FROM quay.io/monax/build:0.17
MAINTAINER Monax <support@monax.io>

ARG RELEASE
ARG TARGET
ENV TARGET_URL github.com/monax/$TARGET
ENV REPO $GOPATH/src/$TARGET_URL

COPY . $REPO
WORKDIR $REPO
RUN go build --ldflags '-extldflags "-static"' -o $INSTALL_BASE/$TARGET github.com/monax/monax/cmd/monax
