#!/usr/bin/env bash
MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TARGET="monax"
IMAGE="quay.io/monax/$TARGET"
RELEASE=${version:-"0.18.0"}
MODIFIER="platform_deployer"

set -e
docker build --tag $IMAGE:$RELEASE-$MODIFIER $MY_DIR
docker push "$IMAGE:$RELEASE-$MODIFIER"