jobs:

- name: deployGSFactory
  deploy:
    contract: GSFactory.sol
    instance: all

- name: createGSContract
  call:
    destination: $deployGSFactory
    data: create
    abi: GSFactory

- name:  getGSAddr
  query-contract:
    destination: $deployGSFactory
    data: getLast
    abi: $deployGSFactory

- name: assertAddr
  assert:
    key: $getGSAddr
    relation: eq
    val: $createGSContract

- name: setStorage
  call:
    destination: $createGSContract
    data: set $setStorageBase
    abi: GSContract

- name: queryStorage
  query-contract:
    destination: $createGSContract
    data: get
    abi: GSContract

- name: assertStorage
  assert:
    key: $queryStorage
    relation: eq
    val: $setStorageBase
